name: Check & Test

on:
  pull_request:
    branches: main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RISC0_TOOLCHAIN_VERSION: v2024-04-22.0
  RISC0_MONOREPO_REF: "release-1.0"

jobs:
  check:
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    runs-on: [self-hosted, prod, Linux, X64, cpu]
    steps:
      - uses: actions/checkout@v4
        with:
          # Full history is required by license-check.py
          fetch-depth: 0
          submodules: recursive
      - uses: risc0/risc0/.github/actions/rustup@main
      - name: Install cargo-sort
        uses: risc0/cargo-install@b9307573043522ab0d3e3be64a51763b765b52a4
        with:
          crate: cargo-sort
          version: "1.0"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "v1.0.0"
      - run: cargo fmt --all --check
      - run: cargo sort --workspace --check
      - run: cargo clippy -p blobstream0-primitives
      - run: forge fmt --check
        working-directory: contracts
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python license-check.py
      - name: check for "D0 NOT MERGE" comments
        run: |
          [ "$(grep -re 'DO[_ ]\?NOT[_ ]\?MERGE' $(git ls-tree --full-tree --name-only -r HEAD) | tee /dev/fd/2 | wc -l)" -eq "0" ]
  test:
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    runs-on: [self-hosted, prod, Linux, X64, cpu]
    steps:
      # This is a workaround from: https://github.com/actions/checkout/issues/590#issuecomment-970586842
      - name: checkout dummy commit (submodule bug workaround)
        run: "git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :"

      - name: clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install rust
        uses: risc0/risc0/.github/actions/rustup@main

      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "v1.0.0"

      - name: install rzup
        run: |
          curl -L https://risczero.com/install | bash
          echo "$HOME/.risc0/bin" >> $GITHUB_PATH
        shell: bash

      - name: install rzup components
        run: |
          rzup install --verbose --force cargo-risczero 2.0.2
          rzup install --verbose --force r0vm 2.0.2
          rzup install --verbose --force rust 1.85.0
          rzup install --verbose --force cpp
        shell: bash

      - name: cargo check to build autogenerated files
        run: cargo check

      # Note: check above should rebuild contracts
      # - name: build solidity contracts
      #   run: forge build
      #   working-directory: contracts

      - name: run tests
        run: cargo test

      # - name: run foundry tests in dev mode
      #   env:
      #     RISC0_DEV_MODE: true
      #   run: forge test -vvv
      #   working-directory: contracts
